version: '3.8'

services:
  app:
    image: kokusai-kakeibo
    build:
      context: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    command: ["npm", "run", "start"]
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_NAME=kokusai_kakeibo_dev
      - SESSION_SECRET=aaaa
  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: kokusai_kakeibo_dev